# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3195cbbf64e40590e158eca41037ed5f6833db444230cd2f19f021d6cb0f787700be73b482af903f8abfa202c9c0fc7796c92f1b56505c982468b290a8fafe3

test:
  secret_key_base: 58ebaa54b365ccc9ddfeaae561c7aee6bb0bbe6b21119a3c97dd879789082782cfe81ace8c84f92842cb5cf7a4d19d534b7a37e125c5646ec8fe63615ce12486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
